<?php
/**
 * Created by PhpStorm.
 * User: Graham
 * Date: 6/4/2017
 * Time: 3:24 PM
 */

namespace Nurikabe;


class Nurikabe
{
    const BLANK = 0;
    const SEA = -1;
    const ISLAND = -2;
    const SEAERROR = -3;
    const ISLANDERROR = -4;

    private $name;
    private $game;
    private $solution;
    private $difficulty;
    private $wantsToSolve;
    private $wantsToCheck;
    private $wantsToClear;
    private $json;


    public function getDifficulty(){
        return $this->difficulty;
    }

    public function setDifficulty($difficulty){
        $this->difficulty = $difficulty;
    }

    public function getName(){
        return $this->name;
    }

    public function getWantsToClear(){
        return $this->wantsToClear;
    }

    public function setWantsToClear($wantsToClear){
        $this->wantsToClear = $wantsToClear;
    }

    public function getWantsToSolve(){
        return $this->wantsToSolve;
    }

    public function setWantsToSolve($wantsToSolve){
        $this->wantsToSolve = $wantsToSolve;
    }


    public function setName($name){
        $this->name = $name;
    }

    public function getGameBoard(){
        return $this->game;
    }

    public function getSolution(){
        return $this->solution;
    }

    public function setUpGameBoard(){
            $this->game = array(
                "3x3ultraeasy"=>array(
                    "0,0"=>1,
                    "0,1"=>self::BLANK,
                    "0,2"=>1,
                    "1,0"=>self::BLANK,
                    "1,1"=>self::BLANK,
                    "1,2"=>self::BLANK,
                    "2,0"=>2,
                    "2,1"=>self::BLANK,
                    "2,2"=>self::BLANK),
                "8x8veryeasy"=>array(
                    "0,0"=>self::BLANK,
                    "0,1"=>self::BLANK,
                    "0,2"=>2,
                    "0,3"=>self::BLANK,
                    "0,4"=>self::BLANK,
                    "0,5"=>self::BLANK,
                    "0,6"=>self::BLANK,
                    "0,7"=>self::BLANK,
                    "1,0"=>self::BLANK,
                    "1,1"=>1,
                    "1,2"=>self::BLANK,
                    "1,3"=>self::BLANK,
                    "1,4"=>self::BLANK,
                    "1,5"=>4,
                    "1,6"=>self::BLANK,
                    "1,7"=>self::BLANK,
                    "2,0"=>self::BLANK,
                    "2,1"=>self::BLANK,
                    "2,2"=>self::BLANK,
                    "2,3"=>self::BLANK,
                    "2,4"=>2,
                    "2,5"=>self::BLANK,
                    "2,6"=>self::BLANK,
                    "2,7"=>self::BLANK,
                    "3,0"=>self::BLANK,
                    "3,1"=>2,
                    "3,2"=>self::BLANK,
                    "3,3"=>self::BLANK,
                    "3,4"=>self::BLANK,
                    "3,5"=>self::BLANK,
                    "3,6"=>self::BLANK,
                    "3,7"=>self::BLANK,
                    "4,0"=>4,
                    "4,1"=>self::BLANK,
                    "4,2"=>self::BLANK,
                    "4,3"=>self::BLANK,
                    "4,4"=>self::BLANK,
                    "4,5"=>2,
                    "4,6"=>self::BLANK,
                    "4,7"=>self::BLANK,
                    "5,0"=>self::BLANK,
                    "5,1"=>self::BLANK,
                    "5,2"=>self::BLANK,
                    "5,3"=>self::BLANK,
                    "5,4"=>self::BLANK,
                    "5,5"=>self::BLANK,
                    "5,6"=>self::BLANK,
                    "5,7"=>self::BLANK,
                    "6,0"=>self::BLANK,
                    "6,1"=>self::BLANK,
                    "6,2"=>self::BLANK,
                    "6,3"=>3,
                    "6,4"=>self::BLANK,
                    "6,5"=>self::BLANK,
                    "6,6"=>self::BLANK,
                    "6,7"=>3,
                    "7,0"=>self::BLANK,
                    "7,1"=>self::BLANK,
                    "7,2"=>self::BLANK,
                    "7,3"=>self::BLANK,
                    "7,4"=>self::BLANK,
                    "7,5"=>3,
                    "7,6"=>self::BLANK,
                    "7,7"=>self::BLANK),
                "10x10easy"=>array(
                    "0,0"=>4,
                    "0,1"=>self::BLANK,
                    "0,2"=>self::BLANK,
                    "0,3"=>self::BLANK,
                    "0,4"=>self::BLANK,
                    "0,5"=>self::BLANK,
                    "0,6"=>self::BLANK,
                    "0,7"=>self::BLANK,
                    "0,8"=>self::BLANK,
                    "0,9"=>1,
                    "1,0"=>self::BLANK,
                    "1,1"=>self::BLANK,
                    "1,2"=>self::BLANK,
                    "1,3"=>self::BLANK,
                    "1,4"=>self::BLANK,
                    "1,5"=>self::BLANK,
                    "1,6"=>self::BLANK,
                    "1,7"=>self::BLANK,
                    "1,8"=>self::BLANK,
                    "1,9"=>self::BLANK,
                    "2,0"=>self::BLANK,
                    "2,1"=>self::BLANK,
                    "2,2"=>self::BLANK,
                    "2,3"=>self::BLANK,
                    "2,4"=>self::BLANK,
                    "2,5"=>self::BLANK,
                    "2,6"=>3,
                    "2,7"=>self::BLANK,
                    "2,8"=>3,
                    "2,9"=>self::BLANK,
                    "3,0"=>self::BLANK,
                    "3,1"=>2,
                    "3,2"=>self::BLANK,
                    "3,3"=>3,
                    "3,4"=>self::BLANK,
                    "3,5"=>self::BLANK,
                    "3,6"=>self::BLANK,
                    "3,7"=>self::BLANK,
                    "3,8"=>self::BLANK,
                    "3,9"=>self::BLANK,
                    "4,0"=>1,
                    "4,1"=>self::BLANK,
                    "4,2"=>self::BLANK,
                    "4,3"=>self::BLANK,
                    "4,4"=>4,
                    "4,5"=>self::BLANK,
                    "4,6"=>self::BLANK,
                    "4,7"=>3,
                    "4,8"=>self::BLANK,
                    "4,9"=>self::BLANK,
                    "5,0"=>self::BLANK,
                    "5,1"=>self::BLANK,
                    "5,2"=>2,
                    "5,3"=>self::BLANK,
                    "5,4"=>self::BLANK,
                    "5,5"=>self::BLANK,
                    "5,6"=>self::BLANK,
                    "5,7"=>self::BLANK,
                    "5,8"=>self::BLANK,
                    "5,9"=>5,
                    "6,0"=>self::BLANK,
                    "6,1"=>self::BLANK,
                    "6,2"=>self::BLANK,
                    "6,3"=>self::BLANK,
                    "6,4"=>self::BLANK,
                    "6,5"=>self::BLANK,
                    "6,6"=>self::BLANK,
                    "6,7"=>self::BLANK,
                    "6,8"=>self::BLANK,
                    "6,9"=>self::BLANK,
                    "7,0"=>self::BLANK,
                    "7,1"=>self::BLANK,
                    "7,2"=>self::BLANK,
                    "7,3"=>1,
                    "7,4"=>self::BLANK,
                    "7,5"=>self::BLANK,
                    "7,6"=>self::BLANK,
                    "7,7"=>self::BLANK,
                    "7,8"=>self::BLANK,
                    "7,9"=>self::BLANK,
                    "8,0"=>self::BLANK,
                    "8,1"=>self::BLANK,
                    "8,2"=>4,
                    "8,3"=>self::BLANK,
                    "8,4"=>self::BLANK,
                    "8,5"=>3,
                    "8,6"=>self::BLANK,
                    "8,7"=>self::BLANK,
                    "8,8"=>self::BLANK,
                    "8,9"=>self::BLANK,
                    "9,0"=>self::BLANK,
                    "9,1"=>self::BLANK,
                    "9,2"=>self::BLANK,
                    "9,3"=>self::BLANK,
                    "9,4"=>2,
                    "9,5"=>self::BLANK,
                    "9,6"=>self::BLANK,
                    "9,7"=>self::BLANK,
                    "9,8"=>self::BLANK,
                    "9,9"=>self::BLANK),
                "8x8medium"=>array(
                    "0,0"=>self::BLANK,
                    "0,1"=>self::BLANK,
                    "0,2"=>self::BLANK,
                    "0,3"=>self::BLANK,
                    "0,4"=>self::BLANK,
                    "0,5"=>self::BLANK,
                    "0,6"=>self::BLANK,
                    "0,7"=>self::BLANK,
                    "1,0"=>2,
                    "1,1"=>self::BLANK,
                    "1,2"=>self::BLANK,
                    "1,3"=>self::BLANK,
                    "1,4"=>self::BLANK,
                    "1,5"=>self::BLANK,
                    "1,6"=>self::BLANK,
                    "1,7"=>self::BLANK,
                    "2,0"=>self::BLANK,
                    "2,1"=>4,
                    "2,2"=>self::BLANK,
                    "2,3"=>self::BLANK,
                    "2,4"=>self::BLANK,
                    "2,5"=>self::BLANK,
                    "2,6"=>self::BLANK,
                    "2,7"=>self::BLANK,
                    "3,0"=>self::BLANK,
                    "3,1"=>self::BLANK,
                    "3,2"=>self::BLANK,
                    "3,3"=>self::BLANK,
                    "3,4"=>2,
                    "3,5"=>self::BLANK,
                    "3,6"=>self::BLANK,
                    "3,7"=>6,
                    "4,0"=>self::BLANK,
                    "4,1"=>self::BLANK,
                    "4,2"=>self::BLANK,
                    "4,3"=>2,
                    "4,4"=>self::BLANK,
                    "4,5"=>self::BLANK,
                    "4,6"=>self::BLANK,
                    "4,7"=>self::BLANK,
                    "5,0"=>self::BLANK,
                    "5,1"=>2,
                    "5,2"=>self::BLANK,
                    "5,3"=>self::BLANK,
                    "5,4"=>self::BLANK,
                    "5,5"=>self::BLANK,
                    "5,6"=>self::BLANK,
                    "5,7"=>self::BLANK,
                    "6,0"=>5,
                    "6,1"=>self::BLANK,
                    "6,2"=>self::BLANK,
                    "6,3"=>self::BLANK,
                    "6,4"=>4,
                    "6,5"=>self::BLANK,
                    "6,6"=>self::BLANK,
                    "6,7"=>self::BLANK,
                    "7,0"=>self::BLANK,
                    "7,1"=>self::BLANK,
                    "7,2"=>self::BLANK,
                    "7,3"=>self::BLANK,
                    "7,4"=>self::BLANK,
                    "7,5"=>self::BLANK,
                    "7,6"=>self::BLANK,
                    "7,7"=>self::BLANK)
            );
    }

    public function setSolution(){
        $this->solution = array(
            "3x3ultraeasy"=>array(
                "0,0"=>1,
                "0,1"=>self::SEA,
                "0,2"=>1,
                "1,0"=>self::SEA,
                "1,1"=>self::SEA,
                "1,2"=>self::SEA,
                "2,0"=>2,
                "2,1"=>self::ISLAND,
                "2,2"=>self::SEA),
            "8x8veryeasy"=>array(
                "0,0"=>self::SEA,
                "0,1"=>self::SEA,
                "0,2"=>2,
                "0,3"=>self::ISLAND,
                "0,4"=>self::SEA,
                "0,5"=>self::SEA,
                "0,6"=>self::SEA,
                "0,7"=>self::SEA,
                "1,0"=>self::SEA,
                "1,1"=>1,
                "1,2"=>self::SEA,
                "1,3"=>self::SEA,
                "1,4"=>self::SEA,
                "1,5"=>4,
                "1,6"=>self::ISLAND,
                "1,7"=>self::SEA,
                "2,0"=>self::SEA,
                "2,1"=>self::SEA,
                "2,2"=>self::SEA,
                "2,3"=>self::ISLAND,
                "2,4"=>2,
                "2,5"=>self::SEA,
                "2,6"=>self::ISLAND,
                "2,7"=>self::SEA,
                "3,0"=>self::SEA,
                "3,1"=>2,
                "3,2"=>self::ISLAND,
                "3,3"=>self::SEA,
                "3,4"=>self::SEA,
                "3,5"=>self::SEA,
                "3,6"=>self::ISLAND,
                "3,7"=>self::SEA,
                "4,0"=>4,
                "4,1"=>self::SEA,
                "4,2"=>self::SEA,
                "4,3"=>self::SEA,
                "4,4"=>self::ISLAND,
                "4,5"=>2,
                "4,6"=>self::SEA,
                "4,7"=>self::SEA,
                "5,0"=>self::ISLAND,
                "5,1"=>self::SEA,
                "5,2"=>self::ISLAND,
                "5,3"=>self::SEA,
                "5,4"=>self::SEA,
                "5,5"=>self::SEA,
                "5,6"=>self::SEA,
                "5,7"=>self::ISLAND,
                "6,0"=>self::ISLAND,
                "6,1"=>self::SEA,
                "6,2"=>self::ISLAND,
                "6,3"=>3,
                "6,4"=>self::SEA,
                "6,5"=>self::ISLAND,
                "6,6"=>self::SEA,
                "6,7"=>3,
                "7,0"=>self::ISLAND,
                "7,1"=>self::SEA,
                "7,2"=>self::SEA,
                "7,3"=>self::SEA,
                "7,4"=>self::ISLAND,
                "7,5"=>3,
                "7,6"=>self::SEA,
                "7,7"=>self::ISLAND),
            "10x10easy"=>array(
                "0,0"=>4,
                "0,1"=>self::ISLAND,
                "0,2"=>self::ISLAND,
                "0,3"=>self::ISLAND,
                "0,4"=>self::SEA,
                "0,5"=>self::SEA,
                "0,6"=>self::SEA,
                "0,7"=>self::SEA,
                "0,8"=>self::SEA,
                "0,9"=>1,
                "1,0"=>self::SEA,
                "1,1"=>self::SEA,
                "1,2"=>self::SEA,
                "1,3"=>self::SEA,
                "1,4"=>self::ISLAND,
                "1,5"=>self::ISLAND,
                "1,6"=>self::ISLAND,
                "1,7"=>self::SEA,
                "1,8"=>self::ISLAND,
                "1,9"=>self::SEA,
                "2,0"=>self::SEA,
                "2,1"=>self::ISLAND,
                "2,2"=>self::SEA,
                "2,3"=>self::ISLAND,
                "2,4"=>self::ISLAND,
                "2,5"=>self::SEA,
                "2,6"=>3,
                "2,7"=>self::SEA,
                "2,8"=>3,
                "2,9"=>self::SEA,
                "3,0"=>self::SEA,
                "3,1"=>2,
                "3,2"=>self::SEA,
                "3,3"=>3,
                "3,4"=>self::SEA,
                "3,5"=>self::SEA,
                "3,6"=>self::SEA,
                "3,7"=>self::SEA,
                "3,8"=>self::ISLAND,
                "3,9"=>self::SEA,
                "4,0"=>1,
                "4,1"=>self::SEA,
                "4,2"=>self::SEA,
                "4,3"=>self::SEA,
                "4,4"=>4,
                "4,5"=>self::ISLAND,
                "4,6"=>self::SEA,
                "4,7"=>3,
                "4,8"=>self::SEA,
                "4,9"=>self::SEA,
                "5,0"=>self::SEA,
                "5,1"=>self::SEA,
                "5,2"=>2,
                "5,3"=>self::ISLAND,
                "5,4"=>self::SEA,
                "5,5"=>self::ISLAND,
                "5,6"=>self::SEA,
                "5,7"=>self::ISLAND,
                "5,8"=>self::SEA,
                "5,9"=>5,
                "6,0"=>self::SEA,
                "6,1"=>self::ISLAND,
                "6,2"=>self::SEA,
                "6,4"=>self::SEA,
                "6,3"=>self::SEA,
                "6,5"=>self::ISLAND,
                "6,6"=>self::SEA,
                "6,7"=>self::ISLAND,
                "6,8"=>self::SEA,
                "6,9"=>self::ISLAND,
                "7,0"=>self::SEA,
                "7,1"=>self::ISLAND,
                "7,2"=>self::SEA,
                "7,3"=>1,
                "7,4"=>self::SEA,
                "7,5"=>self::SEA,
                "7,6"=>self::SEA,
                "7,7"=>self::SEA,
                "7,8"=>self::SEA,
                "7,9"=>self::ISLAND,
                "8,0"=>self::SEA,
                "8,1"=>self::ISLAND,
                "8,2"=>4,
                "8,3"=>self::SEA,
                "8,4"=>self::SEA,
                "8,5"=>3,
                "8,6"=>self::ISLAND,
                "8,7"=>self::ISLAND,
                "8,8"=>self::SEA,
                "8,9"=>self::ISLAND,
                "9,0"=>self::SEA,
                "9,1"=>self::SEA,
                "9,2"=>self::SEA,
                "9,3"=>self::ISLAND,
                "9,4"=>2,
                "9,5"=>self::SEA,
                "9,6"=>self::SEA,
                "9,7"=>self::SEA,
                "9,8"=>self::SEA,
                "9,9"=>self::ISLAND),
            "8x8medium"=>array(
                "0,0"=>self::ISLAND,
                "0,1"=>self::SEA,
                "0,2"=>self::SEA,
                "0,3"=>self::SEA,
                "0,4"=>self::SEA,
                "0,5"=>self::SEA,
                "0,6"=>self::SEA,
                "0,7"=>self::SEA,
                "1,0"=>2,
                "1,1"=>self::SEA,
                "1,2"=>self::ISLAND,
                "1,3"=>self::ISLAND,
                "1,4"=>self::SEA,
                "1,5"=>self::ISLAND,
                "1,6"=>self::ISLAND,
                "1,7"=>self::ISLAND,
                "2,0"=>self::SEA,
                "2,1"=>4,
                "2,2"=>self::ISLAND,
                "2,3"=>self::SEA,
                "2,4"=>self::SEA,
                "2,5"=>self::SEA,
                "2,6"=>self::SEA,
                "2,7"=>self::ISLAND,
                "3,0"=>self::SEA,
                "3,1"=>self::SEA,
                "3,2"=>self::SEA,
                "3,3"=>self::SEA,
                "3,4"=>2,
                "3,5"=>self::ISLAND,
                "3,6"=>self::SEA,
                "3,7"=>6,
                "4,0"=>self::SEA,
                "4,1"=>self::ISLAND,
                "4,2"=>self::SEA,
                "4,3"=>2,
                "4,4"=>self::SEA,
                "4,5"=>self::SEA,
                "4,6"=>self::SEA,
                "4,7"=>self::ISLAND,
                "5,0"=>self::SEA,
                "5,1"=>2,
                "5,2"=>self::SEA,
                "5,3"=>self::ISLAND,
                "5,4"=>self::SEA,
                "5,5"=>self::ISLAND,
                "5,6"=>self::SEA,
                "5,7"=>self::SEA,
                "6,0"=>5,
                "6,1"=>self::SEA,
                "6,2"=>self::SEA,
                "6,3"=>self::SEA,
                "6,4"=>4,
                "6,5"=>self::ISLAND,
                "6,6"=>self::ISLAND,
                "6,7"=>self::SEA,
                "7,0"=>self::ISLAND,
                "7,1"=>self::ISLAND,
                "7,2"=>self::ISLAND,
                "7,3"=>self::ISLAND,
                "7,4"=>self::SEA,
                "7,5"=>self::SEA,
                "7,6"=>self::SEA,
                "7,7"=>self::SEA)
        );
    }

    public function clearGame(){
        unset($this->game);
        $this->wantsToClear = false;
        $this->wantsToSolve = false;
        $this->wantsToCheck = false;
    }

    public function setGameBoard($game){
        $this->game = $game;
    }

    public function setJson($json){
        $this->json = $json;
    }

    public function getGameJson(){
        return $this->json;
    }


}